### ISSUE TITLE
ls-interactive Crash Report

### ISSUE THREAD

**Issue by snns2005** [Araxeus/ls-interactive#43]
name = 'ls-interactive'
operating_system = 'windows'
crate_version = '1.5.0'
explanation = '''
Panic occurred in file 'C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\tiny_update_notifier-1.1.0\src\lib.rs' at line 148
'''
cause = 'called `Option::unwrap()` on a `None` value'
method = 'Panic'
backtrace = '''

   0: 0x7ff6486e73f0 - <unresolved>
   1: 0x7ff648707ee5 - <unresolved>
   2: 0x7ff648707fdc - <unresolved>
   3: 0x7ff6486b81ac - <unresolved>
   4: 0x7ff6486ba478 - <unresolved>
   5: 0x7ff6486b9cc4 - <unresolved>
   6: 0x7ff6486f2cec - <unresolved>
   7: 0x7ff9f5287974 - BaseThreadInitThunk
   8: 0x7ff9f7bba271 - RtlUserThreadStart'''

**Comment by Araxeus** [comment]
Sorry about that, the issue is fixed.

I will publish a new version tomorrow, thank you for reporting this :)

> It was actually fixed a while ago, I just forgot to release a new version 😅

**Comment by Araxeus** [comment]
@snns2005 new version was released 😁

https://github.com/Araxeus/ls-interactive/releases/tag/v1.6.0
